### ISSUE TITLE
Highlighter for comments

### ISSUE THREAD

**Issue by DFelten** [bluegray/Highlighter#19]
On some comment formats the highlighter detects a problem:

![image](https://cloud.githubusercontent.com/assets/1169185/16539848/9798ea36-404f-11e6-8b98-dd98e0bb94e1.png)

But this format is correct for comments.

**Comment by bluegray** [comment]
The default regex to highlight should ignore that comment style. Please take a look at the default settings in https://github.com/bluegray/Highlighter/blob/master/highlighter.sublime-settings for an example. 
Since it is the default you could just remove any custom regex settings you have. Also see https://github.com/bluegray/Highlighter/issues/10
